# Required to run your project under the correct environment.
language: php

# Versions of PHP you want your project run with.
php:
  - "5.3"
  - "5.4"
  - "5.5"

before_install:
  - php /home/travis/.phpenv/versions/5.4.25/bin/compser.phar self-update

# Commands to be run before your environment runs.
before_script:
  - composer install

# Commands you want to run that will verify your build.
script: phpunit -- configuration phpunit.xml --coverage-text
